// tpsaprogramminglanguage/menu.component.ts
import { Component, Output, EventEmitter, OnInit } from '@angular/core';
import { BurgerService, Burger } from '../services/burger.service';

@Component({
  selector: 'app-menu',
  templateUrl: './menu.component.html'
})
export class MenuComponent implements OnInit {
  @Output() addToCartEvent = new EventEmitter<Burger>();
  burgers: Burger[] = [];
  loading = true;
  error: string | null = null;

  constructor(private burgerService: BurgerService) {}

  ngOnInit() {
    this.burgerService.getBurgers().subscribe({
      next: (data) => {
        this.burgers = data;
        this.loading = false;
      },
      error: (err) => {
        this.error = 'Failed to load burgers';
        this.loading = false;
      }
    });
  }

  addToCart(burger: Burger): void {
    this.addToCartEvent.emit(burger);
  }
} 
<section class="menu">
  <h2>Our Menu</h2>
  <div *ngIf="loading">Loading...</div>
  <div *ngIf="error">{{error}}</div>
  <div *ngIf="!loading && !error" class="burger-grid">
    <div *ngFor="let burger of burgers" class="burger-card">
      <img [src]="burger.image" [alt]="burger.name">
      <h3>{{burger.name}}</h3>
      <p>{{burger.description}}</p>
      <p class="price">${{burger.price.toFixed(2)}}</p>
      <button (click)="addToCart(burger)">Add to Cart</button>
    </div>
  </div>
</section>

// tpsaprogramminglanguage/components/Menu.jsx
import React, { useState, useEffect } from 'react';

function Menu({ addToCart }) {
  const [burgers, setBurgers] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  useEffect(() => {
    fetch('http://localhost:5000/api/burgers')
      .then(response => response.json())
      .then(data => {
        setBurgers(data);
        setLoading(false);
      })
      .catch(err => {
        setError('Failed to load burgers');
        setLoading(false);
      });
  }, []);

  if (loading) return <div>Loading...</div>;
  if (error) return <div>{error}</div>;

  return (
    <section className="menu">
      <h2>Our Menu</h2>
      <div className="burger-grid">
        {burgers.map((burger) => (
          <div key={burger.id} className="burger-card">
            <img src={burger.image} alt={burger.name} />
            <h3>{burger.name}</h3>
            <p>{burger.description}</p>
            <p className="price">${burger.price.toFixed(2)}</p>
            <button onClick={() => addToCart(burger)}>Add to Cart</button>
          </div>
        ))}
      </div>
    </section>
  );
}

export default Menu;
