// tpsaprogramminglanguage/app.component.ts
import { Component } from '@angular/core';

interface Burger {
  id: number;
  name: string;
  description: string;
  price: number;
  image: string;
}

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  cart: Burger[] = [];

  addToCart(burger: Burger): void {
    this.cart.push(burger);
  }

  removeFromCart(index: number): void {
    this.cart.splice(index, 1);
  }

  checkout(): void {
    if (this.cart.length === 0) {
      alert('Your cart is empty!');
      return;
    }
    
    const total = this.cart.reduce((sum, item) => sum + item.price, 0);
    alert(`Thank you for your order!\nTotal: $${total.toFixed(2)}\nYour burgers will be ready soon!`);
    this.cart = [];
  }
} 
<div class="App">
  <app-header></app-header>
  <main>
    <app-menu (addToCartEvent)="addToCart($event)"></app-menu>
    <app-cart 
      [cart]="cart" 
      (removeFromCartEvent)="removeFromCart($event)"
      (checkoutEvent)="checkout()"
    ></app-cart>
  </main>
  <app-footer></app-footer>
</div>

// tpsaprogramminglanguage/App.jsx
import React, { useState } from 'react';
import './App.css';
import Header from './components/Header';
import Menu from './components/Menu';
import Cart from './components/Cart';
import Footer from './components/Footer';

function App() {
  const [cart, setCart] = useState([]);

  const addToCart = (burger) => {
    setCart([...cart, burger]);
  };

  const removeFromCart = (index) => {
    const newCart = cart.filter((_, i) => i !== index);
    setCart(newCart);
  };

  const checkout = () => {
    if (cart.length === 0) {
      alert('Your cart is empty!');
      return;
    }
    
    const total = cart.reduce((sum, item) => sum + item.price, 0);
    alert(`Thank you for your order!\nTotal: $${total.toFixed(2)}\nYour burgers will be ready soon!`);
    setCart([]);
  };

  return (
    <div className="App">
      <Header />
      <main>
        <Menu addToCart={addToCart} />
        <Cart cart={cart} removeFromCart={removeFromCart} checkout={checkout} />
      </main>
      <Footer />
    </div>
  );
}

export default App;
